### ISSUE TITLE
Error occurs when initializing the environment

### ISSUE THREAD

**Issue by kevin647** [openai/safety-gym#13]
When I make "Safexp-PointGoal1-v0" and execute s= env.reset(), the following error occurs:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/mujoco/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 18, in reset
    return self.env.reset(**kwargs)
  File "/home/user/CIO/safety-gym/safety_gym/envs/engine.py", line 891, in reset
    return self.obs()
  File "/home/user/CIO/safety-gym/safety_gym/envs/engine.py", line 1122, in obs
    assert self.observation_space.contains(obs), f'Bad obs {obs} {self.observation_space}'
AssertionError: Bad obs [ 0.          0.          9.81        0.31878252  0.04484433  0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.27393819  0.          0.          0.          0.68664525  0.43496158
  0.40752401  0.47791412  0.71770926  0.33585917  0.          0.
  0.          0.          0.          0.          0.          0.50541801
  0.69535049  0.43947    -0.21933027 -0.44932642  0.          0.54266448
  0.14696558  0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.3956989   0.          0.          0.        ] Box(-inf, inf, (60,), float32)

my current gym version is '0.23.1' and my python version is 3.7.8

**Comment by nikkostin** [comment]
I had gym version of '0.25.2' and the same exact error appeared. So I downgraded gym to established in the `setup.py` file, i.e. gym=='0.15.3' and now everything works as it should, no more errors.
