### ISSUE TITLE
Error building wheel for mujoco-py

### ISSUE THREAD

**Issue by hodriozola** [openai/safety-gym#15]
Hello everyone,

I'm trying to install Safety Gym on Conda virtual environment (Ubuntu 20.04.4 LTS and Python 3.6.13). I'm having issues with mujoco-py, since it looks like some error is happening while its wheel is building. The error code is the following one:

  **ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpp4lzfm1t build_wheel /tmp/tmpakrcnohb
       cwd: /tmp/pip-install-85me5y04/mujoco-py
  Complete output (21 lines):
  running bdist_wheel
  running build
  Removing old mujoco_py cext /tmp/pip-install-85me5y04/mujoco-py/mujoco_py/generated/cymj_2.0.2.7_38_linuxcpuextensionbuilder_38.so
  Compiling /tmp/pip-install-85me5y04/mujoco-py/mujoco_py/cymj.pyx because it depends on /tmp/pip-build-env-9h71wxn_/overlay/lib/python3.8/site-packages/Cython/Includes/libc/string.pxd.
  [1/1] Cythonizing /tmp/pip-install-85me5y04/mujoco-py/mujoco_py/cymj.pyx
  running build_ext
  building 'mujoco_py.cymj' extension
  creating /tmp/pip-install-85me5y04/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.7_38_linuxcpuextensionbuilder
  creating /tmp/pip-install-85me5y04/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.7_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38
  creating /tmp/pip-install-85me5y04/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.7_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/tmp
  creating /tmp/pip-install-85me5y04/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.7_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/tmp/pip-install-85me5y04
  creating /tmp/pip-install-85me5y04/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.7_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/tmp/pip-install-85me5y04/mujoco-py
  creating /tmp/pip-install-85me5y04/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.7_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/tmp/pip-install-85me5y04/mujoco-py/mujoco_py
  creating /tmp/pip-install-85me5y04/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.7_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/tmp/pip-install-85me5y04/mujoco-py/mujoco_py/gl
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Imujoco_py -I/tmp/pip-install-85me5y04/mujoco-py/mujoco_py -I/home/ikmobility/.mujoco/mujoco200/include -I/tmp/pip-build-env-9h71wxn_/overlay/lib/python3.8/site-packages/numpy/core/include -I/usr/include/python3.8 -c /tmp/pip-install-85me5y04/mujoco-py/mujoco_py/cymj.c -o /tmp/pip-install-85me5y04/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.7_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/tmp/pip-install-85me5y04/mujoco-py/mujoco_py/cymj.o -fopenmp -w
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Imujoco_py -I/tmp/pip-install-85me5y04/mujoco-py/mujoco_py -I/home/ikmobility/.mujoco/mujoco200/include -I/tmp/pip-build-env-9h71wxn_/overlay/lib/python3.8/site-packages/numpy/core/include -I/usr/include/python3.8 -c /tmp/pip-install-85me5y04/mujoco-py/mujoco_py/gl/osmesashim.c -o /tmp/pip-install-85me5y04/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.7_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/tmp/pip-install-85me5y04/mujoco-py/mujoco_py/gl/osmesashim.o -fopenmp -w
  /tmp/pip-install-85me5y04/mujoco-py/mujoco_py/gl/osmesashim.c:1:10: fatal error: GL/osmesa.h: No such file or directory
      1 | #include <GL/osmesa.h>
        |          ^~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for mujoco-py
Successfully built gym
Failed to build mujoco-py
ERROR: Could not build wheels for mujoco-py which use PEP 517 and cannot be installed directly**

I saw that there are other topics open with related issues, but sadly none of them solutions worked for me. I would apreciate if someone could help me. Thanks in advance. Bye.

**Comment by acl21** [comment]
I faced the exact same issue and [this](https://github.com/openai/mujoco-py/issues/132#issuecomment-660992072) worked for me.

**Comment by hodriozola** [comment]
> I faced the exact same issue and [this](https://github.com/openai/mujoco-py/issues/132#issuecomment-660992072) worked for me.

Thanks, it worked. Have a nice day!
